#!/bin/env bash

set -x

export XMONAD_DATA_DIR=./tmp/data
export XMONAD_CONFIG_DIR=./tmp/config
export XMONAD_CACHE_DIR=./tmp/cache

DISPLAY_N=$(( ${DISPLAY:1} + 1))


cabal build && {
    xmonad_path=$(cabal list-bin xmonad)
    Xephyr :$DISPLAY_N -br -ac -noreset -resizeable &
    DISPLAY=:$DISPLAY_N "$xmonad_path"
}
